"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./style/index.css";
import "./style/globals.css";
import "./style/prism-vsc-dark-plus.css";
import { useEffect, useState } from "react";
import { SessionProvider } from "next-auth/react";
import ToasterContext from "@/utils/ToasterContext";
import { ThemeProvider } from "next-themes";
import PreLoader from "@/components/Common/PreLoader";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode; }>) => {
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 1000);
  }, []);


  return (
    <html suppressHydrationWarning={true} className="!scroll-smooth" lang="en">
      <body>
        {loading ? (
          <PreLoader />
        ) : (
          <SessionProvider>
            <ThemeProvider
              attribute="class"
              enableSystem={false}
              defaultTheme="light"
            >
              <ToasterContext />
              <Header />
              {children}
              {/* <Footer /> */}
              {/* <ScrollToTop /> */}
            </ThemeProvider>
          </SessionProvider>
        )}
      </body>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  );
}
export default RootLayout;

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   const [loading, setLoading] = useState<boolean>(true);

//   useEffect(() => {
//     setTimeout(() => setLoading(false), 1000);
//   }, []);


//   return (
//     <html suppressHydrationWarning={true} className="!scroll-smooth" lang="en">
//       <body>
//         {loading ? (
//           <PreLoader />
//         ) : (
//           <SessionProvider>
//             <ThemeProvider
//               attribute="class"
//               enableSystem={false}
//               defaultTheme="light"
//             >
//               <ToasterContext />
//               <Header />
//               {children}
//               {/* <Footer /> */}
//               {/* <ScrollToTop /> */}
//             </ThemeProvider>
//           </SessionProvider>
//         )}
//       </body>
//       {/* <body className={inter.className}>{children}</body> */}
//     </html>
//   );
// }
